# Schlankes Image fuer den ECHTEN G1 (Arme + Haende + Unitree-Loco).
# Basis = Dockerfile.sim MINUS onnxruntime (loco_sim laeuft nur in der Sim),
# MIT Real-Umgebungsvariablen. KEIN livox/MOLA/realsense -- fuer den vollen
# Navigations-Stack weiterhin docker/Dockerfile (g1pilot:v1.1.0) nutzen.
#
# Die Inspire-Haende brauchen KEINE Extra-Bibliothek: das Modbus-TCP-Backend
# (inspire_ftp/modbus_client.py) ist stdlib-only.
FROM ros:humble

ENV DEBIAN_FRONTEND="noninteractive"
ENV TZ="UTC"
ENV ROS_DISTRO=humble
ENV DISPLAY=:0
ENV LIBGL_ALWAYS_INDIRECT=0

RUN apt-get update && apt-get install -yy \
    python3-pip \
    python3-colcon-common-extensions \
    ros-${ROS_DISTRO}-xacro \
    ros-${ROS_DISTRO}-rviz2 \
    ros-${ROS_DISTRO}-joy \
    ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
    ros-${ROS_DISTRO}-rosidl-default-generators \
    ros-${ROS_DISTRO}-tf2-ros \
    ros-${ROS_DISTRO}-tf2-geometry-msgs \
    ros-${ROS_DISTRO}-robot-state-publisher \
    ros-${ROS_DISTRO}-interactive-markers \
    libxkbcommon-x11-0 \
    libxcb-cursor0 \
    libxcb-icccm4 \
    libxcb-image0 \
    libxcb-keysyms1 \
    libxcb-render-util0 \
    libxcb-xinerama0 \
    libxcb-xinput0 \
    libxcb-shape0 \
    git \
  && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip

# unitree_sdk2_python (EXAKT gleicher Commit wie Original-Dockerfile!)
RUN git clone https://github.com/lnotspotl/unitree_sdk2_python.git \
    && cd unitree_sdk2_python \
    && git checkout 7c661d27f4ae064ffd0dd633fd9d5b518ef0b508 \
    && pip3 install -e .

# Python-Pakete (arm_controller braucht pin/pinocchio, joystick braucht evdev,
# inspire_hand-Bridge braucht websockets fuer die HTML-GUIs)
RUN pip3 install pyqt6 "pin>=2.6" meshcat evdev numpy websockets

# astroviz_interfaces (PFLICHT: robot_state.py importiert MotorState daraus)
RUN mkdir -p /ros2_ws/src
WORKDIR /ros2_ws/src
RUN git clone https://github.com/CDonosoK/astroviz_interfaces.git

WORKDIR /ros2_ws
RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
    colcon build --packages-select astroviz_interfaces

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /root/.bashrc && \
    echo "source /ros2_ws/install/setup.bash" >> /root/.bashrc && \
    echo "export LD_LIBRARY_PATH=/usr/local/lib:\$LD_LIBRARY_PATH" >> /root/.bashrc

# Real-Mode Umgebungsvariablen. DDS-Konvention (utils/common.py):
#   Unitree-DDS = Domain 0 auf ROBOT_INTERFACE (der G1 sendet fest auf 0)
#   ROS-Graph   = Domain 1 auf loopback (cyclonedds.xml)
# Beides in EINEM Prozess geht nur mit UNTERSCHIEDLICHEN Domains -- exakt
# spiegelbildlich zur Sim (dort ROS=0 / Unitree=1).
ENV ROS_DOMAIN_ID=1
ENV UNITREE_DOMAIN_ID=0
ENV G1_SIM_MODE=false

# CycloneDDS Loopback-Konfiguration fuer den ROS-Graph (alle Nodes laufen im
# selben Host-Netz-Container -> loopback reicht und haelt ROS-Traffic vom
# Roboter-LAN/WLAN fern). Das Unitree-SDK ist davon UNBERUEHRT: es baut seine
# CycloneDDS-Config selbst (ChannelFactoryInitialize bindet ROBOT_INTERFACE
# direkt) und ignoriert CYCLONEDDS_URI.
COPY docker/cyclonedds.xml /etc/cyclonedds.xml
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
ENV CYCLONEDDS_URI=file:///etc/cyclonedds.xml

WORKDIR /workspace
CMD ["bash"]
